// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ozonmp/ise-apartment-api/internal/repo (interfaces: Repo)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	apartment "github.com/ozonmp/ise-apartment-api/internal/model"
)

// MockRepo is a mock of Repo interface.
type MockRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRepoMockRecorder
}

// MockRepoMockRecorder is the mock recorder for MockRepo.
type MockRepoMockRecorder struct {
	mock *MockRepo
}

// NewMockRepo creates a new mock instance.
func NewMockRepo(ctrl *gomock.Controller) *MockRepo {
	mock := &MockRepo{ctrl: ctrl}
	mock.recorder = &MockRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepo) EXPECT() *MockRepoMockRecorder {
	return m.recorder
}

// DescribeApartment mocks base method.
func (m *MockRepo) DescribeApartment(arg0 context.Context, arg1 uint64) (*apartment.Apartment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeApartment", arg0, arg1)
	ret0, _ := ret[0].(*apartment.Apartment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeApartment indicates an expected call of DescribeApartment.
func (mr *MockRepoMockRecorder) DescribeApartment(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeApartment", reflect.TypeOf((*MockRepo)(nil).DescribeApartment), arg0, arg1)
}
