project:
  name: Ozon Code Platform Apartment API
  debug: true
  environment: development

grpc:
  host: 0.0.0.0
  port: 8082
  maxConnectionIdle: 5 # Minutes
  timeout: 15 # Seconds
  maxConnectionAge: 5 # Minutes

rest:
  host: 0.0.0.0
  port: 8080
  allowedCorsOrigins:
    - "http://localhost:8081"
    - "http://0.0.0.0:8081"
    - "http://127.0.0.1:8081"

metrics:
  host: 0.0.0.0
  port: 9100
  path: /metrics

jaeger:
  service: "ise-apartment-api"
  host: "jaeger"
  port: ":6831"

status:
  host: 0.0.0.0
  port: 8000
  livenessPath: /live
  readinessPath: /ready
  versionPath: /version

database:
  dsn: "host=postgres port=5432 user=user password=password dbname=apartment_db sslmode=disable"
  migrations: "migrations/migrations"
  driver: pgx

kafka:
  capacity: 512
  topic: "ise-apartment-events"
  groupId: "ise-apartment-api"
  brokers:
    - "kafka:9092"
    - "localhost:9094"
