# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: ozonmp/ise_apartment_api/v1/ise_apartment_api.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import validate.validate_pb2
import google.api.annotations_pb2
import google.protobuf.timestamp_pb2
import ozonmp.ise_apartment_api.v1.ise_apartment_api_pb2


class IseApartmentApiServiceBase(abc.ABC):

    @abc.abstractmethod
    async def DescribeApartmentV1(self, stream: 'grpclib.server.Stream[ozonmp.ise_apartment_api.v1.ise_apartment_api_pb2.DescribeApartmentV1Request, ozonmp.ise_apartment_api.v1.ise_apartment_api_pb2.DescribeApartmentV1Response]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/ozonmp.ise_apartment_api.v1.IseApartmentApiService/DescribeApartmentV1': grpclib.const.Handler(
                self.DescribeApartmentV1,
                grpclib.const.Cardinality.UNARY_UNARY,
                ozonmp.ise_apartment_api.v1.ise_apartment_api_pb2.DescribeApartmentV1Request,
                ozonmp.ise_apartment_api.v1.ise_apartment_api_pb2.DescribeApartmentV1Response,
            ),
        }


class IseApartmentApiServiceStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.DescribeApartmentV1 = grpclib.client.UnaryUnaryMethod(
            channel,
            '/ozonmp.ise_apartment_api.v1.IseApartmentApiService/DescribeApartmentV1',
            ozonmp.ise_apartment_api.v1.ise_apartment_api_pb2.DescribeApartmentV1Request,
            ozonmp.ise_apartment_api.v1.ise_apartment_api_pb2.DescribeApartmentV1Response,
        )
