# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ozonmp/ise_apartment_api/v1/ise_apartment_api.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from validate import validate_pb2 as validate_dot_validate__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ozonmp/ise_apartment_api/v1/ise_apartment_api.proto',
  package='ozonmp.ise_apartment_api.v1',
  syntax='proto3',
  serialized_options=_b('ZKgithub.com/ozonmp/ise-apartment-api/pkg/ise-apartment-api;ise_apartment_api'),
  serialized_pb=_b('\n3ozonmp/ise_apartment_api/v1/ise_apartment_api.proto\x12\x1bozonmp.ise_apartment_api.v1\x1a\x17validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x7f\n\tApartment\x12\x0e\n\x02id\x18\x01 \x01(\x04R\x02id\x12\x16\n\x06object\x18\x02 \x01(\tR\x06object\x12\x14\n\x05owner\x18\x03 \x01(\tR\x05owner\x12\x34\n\x07\x63reated\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x07\x63reated\"H\n\x1a\x44\x65scribeApartmentV1Request\x12*\n\x0c\x61partment_id\x18\x01 \x01(\x04\x42\x07\xfa\x42\x04\x32\x02 \x00R\x0b\x61partmentId\"[\n\x1b\x44\x65scribeApartmentV1Response\x12<\n\x05value\x18\x01 \x01(\x0b\x32&.ozonmp.ise_apartment_api.v1.ApartmentR\x05value2\xca\x01\n\x16IseApartmentApiService\x12\xaf\x01\n\x13\x44\x65scribeApartmentV1\x12\x37.ozonmp.ise_apartment_api.v1.DescribeApartmentV1Request\x1a\x38.ozonmp.ise_apartment_api.v1.DescribeApartmentV1Response\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/v1/apartments/{apartment_id}BMZKgithub.com/ozonmp/ise-apartment-api/pkg/ise-apartment-api;ise_apartment_apib\x06proto3')
  ,
  dependencies=[validate_dot_validate__pb2.DESCRIPTOR,google_dot_api_dot_annotations__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_APARTMENT = _descriptor.Descriptor(
  name='Apartment',
  full_name='ozonmp.ise_apartment_api.v1.Apartment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ozonmp.ise_apartment_api.v1.Apartment.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='id', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='object', full_name='ozonmp.ise_apartment_api.v1.Apartment.object', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='object', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='owner', full_name='ozonmp.ise_apartment_api.v1.Apartment.owner', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='owner', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='created', full_name='ozonmp.ise_apartment_api.v1.Apartment.created', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='created', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=172,
  serialized_end=299,
)


_DESCRIBEAPARTMENTV1REQUEST = _descriptor.Descriptor(
  name='DescribeApartmentV1Request',
  full_name='ozonmp.ise_apartment_api.v1.DescribeApartmentV1Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='apartment_id', full_name='ozonmp.ise_apartment_api.v1.DescribeApartmentV1Request.apartment_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\372B\0042\002 \000'), json_name='apartmentId', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=301,
  serialized_end=373,
)


_DESCRIBEAPARTMENTV1RESPONSE = _descriptor.Descriptor(
  name='DescribeApartmentV1Response',
  full_name='ozonmp.ise_apartment_api.v1.DescribeApartmentV1Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='ozonmp.ise_apartment_api.v1.DescribeApartmentV1Response.value', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='value', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=375,
  serialized_end=466,
)

_APARTMENT.fields_by_name['created'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_DESCRIBEAPARTMENTV1RESPONSE.fields_by_name['value'].message_type = _APARTMENT
DESCRIPTOR.message_types_by_name['Apartment'] = _APARTMENT
DESCRIPTOR.message_types_by_name['DescribeApartmentV1Request'] = _DESCRIBEAPARTMENTV1REQUEST
DESCRIPTOR.message_types_by_name['DescribeApartmentV1Response'] = _DESCRIBEAPARTMENTV1RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Apartment = _reflection.GeneratedProtocolMessageType('Apartment', (_message.Message,), dict(
  DESCRIPTOR = _APARTMENT,
  __module__ = 'ozonmp.ise_apartment_api.v1.ise_apartment_api_pb2'
  # @@protoc_insertion_point(class_scope:ozonmp.ise_apartment_api.v1.Apartment)
  ))
_sym_db.RegisterMessage(Apartment)

DescribeApartmentV1Request = _reflection.GeneratedProtocolMessageType('DescribeApartmentV1Request', (_message.Message,), dict(
  DESCRIPTOR = _DESCRIBEAPARTMENTV1REQUEST,
  __module__ = 'ozonmp.ise_apartment_api.v1.ise_apartment_api_pb2'
  # @@protoc_insertion_point(class_scope:ozonmp.ise_apartment_api.v1.DescribeApartmentV1Request)
  ))
_sym_db.RegisterMessage(DescribeApartmentV1Request)

DescribeApartmentV1Response = _reflection.GeneratedProtocolMessageType('DescribeApartmentV1Response', (_message.Message,), dict(
  DESCRIPTOR = _DESCRIBEAPARTMENTV1RESPONSE,
  __module__ = 'ozonmp.ise_apartment_api.v1.ise_apartment_api_pb2'
  # @@protoc_insertion_point(class_scope:ozonmp.ise_apartment_api.v1.DescribeApartmentV1Response)
  ))
_sym_db.RegisterMessage(DescribeApartmentV1Response)


DESCRIPTOR._options = None
_DESCRIBEAPARTMENTV1REQUEST.fields_by_name['apartment_id']._options = None

_ISEAPARTMENTAPISERVICE = _descriptor.ServiceDescriptor(
  name='IseApartmentApiService',
  full_name='ozonmp.ise_apartment_api.v1.IseApartmentApiService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=469,
  serialized_end=671,
  methods=[
  _descriptor.MethodDescriptor(
    name='DescribeApartmentV1',
    full_name='ozonmp.ise_apartment_api.v1.IseApartmentApiService.DescribeApartmentV1',
    index=0,
    containing_service=None,
    input_type=_DESCRIBEAPARTMENTV1REQUEST,
    output_type=_DESCRIBEAPARTMENTV1RESPONSE,
    serialized_options=_b('\202\323\344\223\002\037\022\035/v1/apartments/{apartment_id}'),
  ),
])
_sym_db.RegisterServiceDescriptor(_ISEAPARTMENTAPISERVICE)

DESCRIPTOR.services_by_name['IseApartmentApiService'] = _ISEAPARTMENTAPISERVICE

# @@protoc_insertion_point(module_scope)
