// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: ozonmp/ise_apartment_api/v1/ise_apartment_api.proto

package ise_apartment_api

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
)

// Validate checks the field values on Apartment with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *Apartment) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Id

	// no validation rules for Object

	// no validation rules for Owner

	if v, ok := interface{}(m.GetCreated()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ApartmentValidationError{
				field:  "Created",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// ApartmentValidationError is the validation error returned by
// Apartment.Validate if the designated constraints aren't met.
type ApartmentValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ApartmentValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ApartmentValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ApartmentValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ApartmentValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ApartmentValidationError) ErrorName() string { return "ApartmentValidationError" }

// Error satisfies the builtin error interface
func (e ApartmentValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sApartment.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ApartmentValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ApartmentValidationError{}

// Validate checks the field values on DescribeApartmentV1Request with the
// rules defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *DescribeApartmentV1Request) Validate() error {
	if m == nil {
		return nil
	}

	if m.GetApartmentId() <= 0 {
		return DescribeApartmentV1RequestValidationError{
			field:  "ApartmentId",
			reason: "value must be greater than 0",
		}
	}

	return nil
}

// DescribeApartmentV1RequestValidationError is the validation error returned
// by DescribeApartmentV1Request.Validate if the designated constraints aren't met.
type DescribeApartmentV1RequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DescribeApartmentV1RequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DescribeApartmentV1RequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DescribeApartmentV1RequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DescribeApartmentV1RequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DescribeApartmentV1RequestValidationError) ErrorName() string {
	return "DescribeApartmentV1RequestValidationError"
}

// Error satisfies the builtin error interface
func (e DescribeApartmentV1RequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDescribeApartmentV1Request.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DescribeApartmentV1RequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DescribeApartmentV1RequestValidationError{}

// Validate checks the field values on DescribeApartmentV1Response with the
// rules defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *DescribeApartmentV1Response) Validate() error {
	if m == nil {
		return nil
	}

	if v, ok := interface{}(m.GetValue()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DescribeApartmentV1ResponseValidationError{
				field:  "Value",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// DescribeApartmentV1ResponseValidationError is the validation error returned
// by DescribeApartmentV1Response.Validate if the designated constraints
// aren't met.
type DescribeApartmentV1ResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DescribeApartmentV1ResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DescribeApartmentV1ResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DescribeApartmentV1ResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DescribeApartmentV1ResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DescribeApartmentV1ResponseValidationError) ErrorName() string {
	return "DescribeApartmentV1ResponseValidationError"
}

// Error satisfies the builtin error interface
func (e DescribeApartmentV1ResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDescribeApartmentV1Response.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DescribeApartmentV1ResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DescribeApartmentV1ResponseValidationError{}
