// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: ozonmp/ise_apartment_api/v1/ise_apartment_api.proto

package ise_apartment_api

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
)

// Validate checks the field values on Apartment with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *Apartment) Validate() error {
	if m == nil {
		return nil
	}

	if m.GetId() <= 0 {
		return ApartmentValidationError{
			field:  "Id",
			reason: "value must be greater than 0",
		}
	}

	if l := utf8.RuneCountInString(m.GetObject()); l < 1 || l > 1000 {
		return ApartmentValidationError{
			field:  "Object",
			reason: "value length must be between 1 and 1000 runes, inclusive",
		}
	}

	if l := utf8.RuneCountInString(m.GetOwner()); l < 1 || l > 1000 {
		return ApartmentValidationError{
			field:  "Owner",
			reason: "value length must be between 1 and 1000 runes, inclusive",
		}
	}

	return nil
}

// ApartmentValidationError is the validation error returned by
// Apartment.Validate if the designated constraints aren't met.
type ApartmentValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ApartmentValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ApartmentValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ApartmentValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ApartmentValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ApartmentValidationError) ErrorName() string { return "ApartmentValidationError" }

// Error satisfies the builtin error interface
func (e ApartmentValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sApartment.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ApartmentValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ApartmentValidationError{}

// Validate checks the field values on DescribeApartmentV1Request with the
// rules defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *DescribeApartmentV1Request) Validate() error {
	if m == nil {
		return nil
	}

	if m.GetApartmentId() <= 0 {
		return DescribeApartmentV1RequestValidationError{
			field:  "ApartmentId",
			reason: "value must be greater than 0",
		}
	}

	return nil
}

// DescribeApartmentV1RequestValidationError is the validation error returned
// by DescribeApartmentV1Request.Validate if the designated constraints aren't met.
type DescribeApartmentV1RequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DescribeApartmentV1RequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DescribeApartmentV1RequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DescribeApartmentV1RequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DescribeApartmentV1RequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DescribeApartmentV1RequestValidationError) ErrorName() string {
	return "DescribeApartmentV1RequestValidationError"
}

// Error satisfies the builtin error interface
func (e DescribeApartmentV1RequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDescribeApartmentV1Request.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DescribeApartmentV1RequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DescribeApartmentV1RequestValidationError{}

// Validate checks the field values on DescribeApartmentV1Response with the
// rules defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *DescribeApartmentV1Response) Validate() error {
	if m == nil {
		return nil
	}

	if v, ok := interface{}(m.GetValue()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DescribeApartmentV1ResponseValidationError{
				field:  "Value",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// DescribeApartmentV1ResponseValidationError is the validation error returned
// by DescribeApartmentV1Response.Validate if the designated constraints
// aren't met.
type DescribeApartmentV1ResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DescribeApartmentV1ResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DescribeApartmentV1ResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DescribeApartmentV1ResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DescribeApartmentV1ResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DescribeApartmentV1ResponseValidationError) ErrorName() string {
	return "DescribeApartmentV1ResponseValidationError"
}

// Error satisfies the builtin error interface
func (e DescribeApartmentV1ResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDescribeApartmentV1Response.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DescribeApartmentV1ResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DescribeApartmentV1ResponseValidationError{}

// Validate checks the field values on CreateApartmentV1Request with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *CreateApartmentV1Request) Validate() error {
	if m == nil {
		return nil
	}

	if m.GetValue() == nil {
		return CreateApartmentV1RequestValidationError{
			field:  "Value",
			reason: "value is required",
		}
	}

	if v, ok := interface{}(m.GetValue()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateApartmentV1RequestValidationError{
				field:  "Value",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// CreateApartmentV1RequestValidationError is the validation error returned by
// CreateApartmentV1Request.Validate if the designated constraints aren't met.
type CreateApartmentV1RequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateApartmentV1RequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateApartmentV1RequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateApartmentV1RequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateApartmentV1RequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateApartmentV1RequestValidationError) ErrorName() string {
	return "CreateApartmentV1RequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateApartmentV1RequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateApartmentV1Request.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateApartmentV1RequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateApartmentV1RequestValidationError{}

// Validate checks the field values on CreateApartmentV1Response with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *CreateApartmentV1Response) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for ApartmentId

	return nil
}

// CreateApartmentV1ResponseValidationError is the validation error returned by
// CreateApartmentV1Response.Validate if the designated constraints aren't met.
type CreateApartmentV1ResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateApartmentV1ResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateApartmentV1ResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateApartmentV1ResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateApartmentV1ResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateApartmentV1ResponseValidationError) ErrorName() string {
	return "CreateApartmentV1ResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreateApartmentV1ResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateApartmentV1Response.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateApartmentV1ResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateApartmentV1ResponseValidationError{}

// Validate checks the field values on ListApartmentsV1Request with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *ListApartmentsV1Request) Validate() error {
	if m == nil {
		return nil
	}

	if v, ok := interface{}(m.GetParams()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListApartmentsV1RequestValidationError{
				field:  "Params",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// ListApartmentsV1RequestValidationError is the validation error returned by
// ListApartmentsV1Request.Validate if the designated constraints aren't met.
type ListApartmentsV1RequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListApartmentsV1RequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListApartmentsV1RequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListApartmentsV1RequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListApartmentsV1RequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListApartmentsV1RequestValidationError) ErrorName() string {
	return "ListApartmentsV1RequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListApartmentsV1RequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListApartmentsV1Request.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListApartmentsV1RequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListApartmentsV1RequestValidationError{}

// Validate checks the field values on ListApartmentsV1Response with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *ListApartmentsV1Response) Validate() error {
	if m == nil {
		return nil
	}

	for idx, item := range m.GetItems() {
		_, _ = idx, item

		if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListApartmentsV1ResponseValidationError{
					field:  fmt.Sprintf("Items[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	return nil
}

// ListApartmentsV1ResponseValidationError is the validation error returned by
// ListApartmentsV1Response.Validate if the designated constraints aren't met.
type ListApartmentsV1ResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListApartmentsV1ResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListApartmentsV1ResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListApartmentsV1ResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListApartmentsV1ResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListApartmentsV1ResponseValidationError) ErrorName() string {
	return "ListApartmentsV1ResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListApartmentsV1ResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListApartmentsV1Response.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListApartmentsV1ResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListApartmentsV1ResponseValidationError{}

// Validate checks the field values on RemoveApartmentV1Request with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *RemoveApartmentV1Request) Validate() error {
	if m == nil {
		return nil
	}

	if m.GetApartmentId() <= 0 {
		return RemoveApartmentV1RequestValidationError{
			field:  "ApartmentId",
			reason: "value must be greater than 0",
		}
	}

	return nil
}

// RemoveApartmentV1RequestValidationError is the validation error returned by
// RemoveApartmentV1Request.Validate if the designated constraints aren't met.
type RemoveApartmentV1RequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RemoveApartmentV1RequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RemoveApartmentV1RequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RemoveApartmentV1RequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RemoveApartmentV1RequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RemoveApartmentV1RequestValidationError) ErrorName() string {
	return "RemoveApartmentV1RequestValidationError"
}

// Error satisfies the builtin error interface
func (e RemoveApartmentV1RequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRemoveApartmentV1Request.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RemoveApartmentV1RequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RemoveApartmentV1RequestValidationError{}

// Validate checks the field values on RemoveApartmentV1Response with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *RemoveApartmentV1Response) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Found

	return nil
}

// RemoveApartmentV1ResponseValidationError is the validation error returned by
// RemoveApartmentV1Response.Validate if the designated constraints aren't met.
type RemoveApartmentV1ResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RemoveApartmentV1ResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RemoveApartmentV1ResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RemoveApartmentV1ResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RemoveApartmentV1ResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RemoveApartmentV1ResponseValidationError) ErrorName() string {
	return "RemoveApartmentV1ResponseValidationError"
}

// Error satisfies the builtin error interface
func (e RemoveApartmentV1ResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRemoveApartmentV1Response.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RemoveApartmentV1ResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RemoveApartmentV1ResponseValidationError{}

// Validate checks the field values on
// ListApartmentsV1Request_ListApartmentsParams with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *ListApartmentsV1Request_ListApartmentsParams) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Offset

	// no validation rules for Limit

	// no validation rules for Object

	// no validation rules for Owner

	return nil
}

// ListApartmentsV1Request_ListApartmentsParamsValidationError is the
// validation error returned by
// ListApartmentsV1Request_ListApartmentsParams.Validate if the designated
// constraints aren't met.
type ListApartmentsV1Request_ListApartmentsParamsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListApartmentsV1Request_ListApartmentsParamsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListApartmentsV1Request_ListApartmentsParamsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListApartmentsV1Request_ListApartmentsParamsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListApartmentsV1Request_ListApartmentsParamsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListApartmentsV1Request_ListApartmentsParamsValidationError) ErrorName() string {
	return "ListApartmentsV1Request_ListApartmentsParamsValidationError"
}

// Error satisfies the builtin error interface
func (e ListApartmentsV1Request_ListApartmentsParamsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListApartmentsV1Request_ListApartmentsParams.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListApartmentsV1Request_ListApartmentsParamsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListApartmentsV1Request_ListApartmentsParamsValidationError{}
